var express = require("express")
var app = express()
var CourseModel = require("./model/Course.js")
var router = require("./router.js")
var db = require("./model/db.js")
app.set("view engine","ejs")
app.get("/",router.showIndex)
app.get("/showCourse",router.showCourses)
app.get("/showAdd",router.showAdd)
app.get("/doAdd",router.doAdd)
app.listen(3000)